[package]
edition = "2021"
name = "entity"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = "0.11.0"
serde = {version = "1", features = ["derive"]}
