[package]
edition = "2021"
name = "introduction_to_yewdux"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo = "0.8"
yew = {version = "0.20", features = ["csr"]}
yewdux = "0.9"
