[package]
edition = "2021"
name = "rustedu-advanced"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["lists", "lifetime", "learn-box", "persistence"]

[dependencies]
